### ISSUE TITLE
Project review - m - ClassMateBot

### ISSUE THREAD

**Issue by anuj672** [bhaveshittadwar/csc-510-se-group-49#1]
# Prospect Project 'm' - ClassMateBot

- Find the rubric [here](https://github.com/txt/se23/blob/main/docs/project2.md)
- Find the project [here](https://github.com/lyonva/ClassMateBot)

### Todo
- Add the review according to the rubric in `proj1/README.md`

**Comment by anuj672** [comment]
https://docs.google.com/spreadsheets/d/1dYphCCj-GT6z4SPsB4Ei85ztgUaG8ymxqzJJ9BXrYF8/edit#gid=0

**Comment by VaibhaviSangawar** [comment]
Completed the grading of the classmate bot app according to the rubrics provided.
