### ISSUE TITLE
Project review - R - Movie Recommender

### ISSUE THREAD

**Issue by bhaveshittadwar** [bhaveshittadwar/csc-510-se-group-49#2]
# Prospect Project 'R' - Movie Recommender

- Find the rubric [here](https://github.com/txt/se23/blob/main/docs/project2.md)
- Find the project [here](https://github.com/git-ankit/MovieRecommender)

### Todo
- Add the review according to the rubric in `proj1/README.md`

**Comment by VaibhaviSangawar** [comment]
Completed the grading of the movie recommender app according to the rubrics provided.
