### ISSUE TITLE
Project review - j - Poll me

### ISSUE THREAD

**Issue by bhaveshittadwar** [bhaveshittadwar/csc-510-se-group-49#3]
# Prospect Project 'j' - Poll me

- Find the rubric [here](https://github.com/txt/se23/blob/main/docs/project2.md)
- Find the project [here](https://github.com/apurva-s/polly)

### Todo
- Add the review according to the rubric in `proj1/README.md`

**Comment by bhaveshittadwar** [comment]
This project is currently working on my local machine.

**Comment by bhaveshittadwar** [comment]
Please review the rubric entries here -> https://docs.google.com/spreadsheets/d/1UQ9X9cUK95PDT2C-c90YVw79zYy4ZpF0H6M6Jt_a-H8/edit?usp=sharing

**Comment by VaibhaviSangawar** [comment]
Reviewed. Looks good.
