### ISSUE TITLE
add codecoverage, formatter and syntax checker in gtihub actions

### ISSUE THREAD

**Issue by anuj672** [bhaveshittadwar/csc-510-se-group-49#31]

**Comment by anuj672** [comment]
Based on the discussion we had -> we have decided to have a codecov cap of 80% , ie the action will fail if the tests donot cover 80% of the code, black to format and pylint for syntax checks with disabled checks for null function retun values

**Comment by bhaveshittadwar** [comment]
sounds effective! 🚀👌🏼 @anuj672
