### ISSUE TITLE
Project review - g - MyDollarBot

### ISSUE THREAD

**Issue by bhaveshittadwar** [bhaveshittadwar/csc-510-se-group-49#4]
# Prospect Project 'g' - MyDollarBot

- Find the rubric [here](https://github.com/txt/se23/blob/main/docs/project2.md)
- Find the project [here](https://github.com/prithvish-doshi-17/MyDollarBot-BOTGo)

### Todo
- Add the review according to the rubric in `proj1/README.md`

**Comment by anuj672** [comment]
Based on discussion on discord it looks like we have to even to points from the sustainability form. Putting back to in progress

**Comment by anuj672** [comment]
https://docs.google.com/spreadsheets/d/1C3dbaBabMKAaYQIRF3Mwthghm-1Af-NMhDlugY7ykCo/edit#gid=0

**Comment by anuj672** [comment]
Projects works on my local machine
Project test cases run as expected except 2 test cases are failing

**Comment by itsJash** [comment]
Everything Looks good
