### ISSUE TITLE
Project review - h - calorieApp

### ISSUE THREAD

**Issue by bhaveshittadwar** [bhaveshittadwar/csc-510-se-group-49#5]
# Prospect Project 'h' - calorieApp

- Find the rubric [here](https://github.com/txt/se23/blob/main/docs/project2.md)
- Find the project [here](https://github.com/Team-Glare/calorieApp_server)

### Todo
- Add the review according to the rubric in `proj1/README.md`

**Comment by itsJash** [comment]
https://docs.google.com/spreadsheets/d/1fEvqFnIYvqIruDfprFrkwHpliJxySkcSFNgc9_ijC1c/edit#gid=0

Rubric_CalorieApp

**Comment by anuj672** [comment]
Hi 
this is not public

**Comment by itsJash** [comment]
Updated. Please Check
Thanks

**Comment by bhaveshittadwar** [comment]
Reviewed. All good 👍
