### ISSUE TITLE
Create a 2 min video and upload to youtube

### ISSUE THREAD

**Issue by anuj672** [bhaveshittadwar/csc-510-se-group-49#7]

**Comment by anuj672** [comment]
https://youtu.be/EUrRv3wOszg 

Hi @VaibhaviSangawar  can you review this? let me know if you find it ok

**Comment by VaibhaviSangawar** [comment]
Hi @anuj672 the video looks good. Do we need to give an overview of the app at the beginning? Like what the app is about before showing the working?

**Comment by anuj672** [comment]
based on the discussion -  we decided to keep the same video due to time constraint of 2 mins
